import torch
import torch.nn as nn
from torchvision.models import ResNet18_Weights, resnet18


class HypernetworkMLP(nn.Module):
    """Preference-conditioned hypernetwork Ψ (Eq. 5).

    3-hidden-layer MLP mapping a preference vector α to the flattened
    (W, b) parameters of the classifier head.
    """

    def __init__(self, preference_dim: int, hidden_dim: int, output_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(preference_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
        )

    def expand_output_dim(self, old_C: int, new_C: int, D: int) -> None:
        """Expand net[-1] when the classifier head grows.

        net[-1] is Linear(hidden_dim → output_dim).  output_dim grows from
        old_C*D+old_C to new_C*D+new_C; hidden_dim is unchanged.
        weight.shape = (output_dim, hidden_dim) → row-indexed.
        bias.shape   = (output_dim,)            → row-indexed.

        Row layout: [W_flat (C*D) | b_flat (C)]
        """
        old = self.net[-1]
        new_out = new_C * D + new_C
        new = nn.Linear(old.in_features, new_out)
        with torch.no_grad():
            new.weight.data[: old_C * D] = old.weight.data[: old_C * D]
            new.bias.data[: old_C * D] = old.bias.data[: old_C * D]
            new.weight.data[new_C * D : new_C * D + old_C] = old.weight.data[
                old_C * D :
            ]
            new.bias.data[new_C * D : new_C * D + old_C] = old.bias.data[old_C * D :]
        self.net[-1] = new

    def forward(self, preference):
        return self.net(preference)


class PreferenceConditionedModel(nn.Module):
    """Shared encoder + preference-conditioned classifier (Figure 2).

    ``fθ(x; α) = W(α)·h(x) + b(α)`` where ``h`` is the backbone feature
    extractor and ``W(α), b(α) = Ψ(α)`` are generated by the hypernetwork.
    """

    def __init__(
        self,
        num_classes: int,
        backbone_name: str = "resnet18",
        preference_dim: int = 2,
        hidden_dim: int = 100,
    ):
        super().__init__()
        self.num_classes = num_classes
        self.preference_dim = preference_dim
        self.hidden_dim = hidden_dim

        if backbone_name == "resnet18":
            # CIFAR-adapted ResNet-18: 3x3 conv, stride=1, no maxpool (for 32x32)
            base_model = resnet18(weights=ResNet18_Weights.DEFAULT)
            base_model.conv1 = nn.Conv2d(
                3, 64, kernel_size=3, stride=1, padding=1, bias=False
            )
            base_model.maxpool = nn.Identity()
            self.backbone = nn.Sequential(*list(base_model.children())[:-1])
            self.feature_dim = 512

        elif backbone_name == "resnet18_tiny":
            # TinyImageNet-adapted ResNet-18: 3x3 conv, stride=1, keep maxpool (for 64x64)
            base_model = resnet18(weights=ResNet18_Weights.DEFAULT)
            base_model.conv1 = nn.Conv2d(
                3, 64, kernel_size=3, stride=1, padding=1, bias=False
            )
            # keep maxpool to downsample 64x64 → 32x32
            self.backbone = nn.Sequential(*list(base_model.children())[:-1])
            self.feature_dim = 512

        else:
            raise ValueError(f"Unknown backbone: {backbone_name}")

        # Hypernetwork generates classifier weights and bias conditioned on α
        total_params = (num_classes * self.feature_dim) + num_classes
        self.hypernetwork = HypernetworkMLP(preference_dim, self.hidden_dim, total_params)

    def expand_head(self, new_num_classes: int) -> None:
        """Expand the hypernetwork output head to accommodate new_num_classes.

        The hypernetwork's final Linear layer is replaced with a wider one.
        Weights for the existing classes are copied; weights for the new
        classes are randomly initialised (Kaiming uniform, the default for
        nn.Linear).

        The output parameter layout is::

            [ W_flat (num_classes * feature_dim) | b_flat (num_classes) ]

        so old class-weight rows occupy indices ``[0 : old_C * D]`` and old
        bias values occupy indices ``[old_C * D : old_C * D + old_C]``.
        After expansion these are copied to the corresponding positions in
        the new layout.

        Args:
            new_num_classes: total number of classes after expansion.
                             Must be strictly greater than the current value.

        Raises:
            ValueError: if ``new_num_classes <= self.num_classes``.
        """
        if new_num_classes <= self.num_classes:
            raise ValueError(
                f"new_num_classes ({new_num_classes}) must be greater than "
                f"current num_classes ({self.num_classes})"
            )

        old_C = self.num_classes
        new_C = new_num_classes
        D = self.feature_dim

        self.hypernetwork.expand_output_dim(old_C, new_C, D)
        self.num_classes = new_C

    def forward(self, x, preference):
        features = self.backbone(x)
        features = features.view(features.size(0), -1)  # (B, feature_dim)

        params = self.hypernetwork(preference)  # (1 or B, total_params)
        params = params[None, :] if params.dim() == 1 else params

        if params.size(0) == 1 and x.size(0) > 1:
            params = params.expand(x.size(0), -1)

        batch_size = x.size(0)
        weights_flat = params[:, : self.num_classes * self.feature_dim]
        bias_flat = params[:, self.num_classes * self.feature_dim :]

        weights = weights_flat.view(batch_size, self.num_classes, self.feature_dim)
        bias = bias_flat.view(batch_size, self.num_classes)

        # (B, num_classes, feature_dim) @ (B, feature_dim, 1) → (B, num_classes)
        logits = torch.bmm(weights, features.unsqueeze(2)).squeeze(2) + bias

        return logits
